In [1]:
%matplotlib inline
import numpy as np
import pandas as pd
import seaborn as sns
from fredapi import Fred
import matplotlib.pyplot as plt
import plotly.express as px
import plotly.io as pio
pio.renderers.default= 'notebook'

In [2]:
API_Key= '97b06b9373640b144d642f8e5c454816'

In [3]:
start_date= '2010-01-01'
end_date= '2025-01-01'

In [4]:
fred= Fred(api_key=API_Key)

In [5]:
## Real GDP

us_gdp= fred.get_series('NGDPRNSAXDCUSQ', observation_start= start_date, observation_end= end_date).to_frame(name='usa')
germany_gdp= fred.get_series('CPMNACNSAB1GQDE', observation_start= start_date, observation_end= end_date).to_frame(name='germany')
india_gdp= fred.get_series('NGDPRNSAXDCINQ', observation_start= start_date, observation_end= end_date).to_frame(name='india')

In [6]:
## Nominal GDP

us_ngdp= fred.get_series('NGDPNSAXDCUSQ', observation_start=start_date, observation_end= end_date).to_frame(name='usa')
germany_ngdp= fred.get_series('NGDPSAXDCDEQ', observation_start=start_date, observation_end= end_date).to_frame(name='germany')
india_ngdp= fred.get_series('NGDPNSAXDCINQ', observation_start=start_date, observation_end= end_date).to_frame(name='india')

In [7]:
nominal_gdp= us_ngdp

for i in [germany_ngdp, india_ngdp]:
    nominal_gdp= pd.merge(nominal_gdp, i, left_index=True, right_index=True, how='inner')

real_gdp= us_gdp

for i in [germany_gdp, india_gdp]:
    real_gdp= pd.merge(real_gdp, i, left_index=True, right_index=True, how='inner')

In [8]:
real_gdp.index.name= 'date'
nominal_gdp.index.name= 'date'

In [9]:
nominal_gdp

                  usa    germany       india
date
2010-01-01  3602418.0   636727.0  18148169.9
2010-04-01  3755370.0   647996.0  17137393.8
2010-07-01  3793867.0   659036.0  17557996.7
2010-10-01  3897315.0   666054.0  20094688.7
2011-01-01  3764835.0   678714.0  21692746.8
...               ...        ...         ...
2024-01-01  7029174.0  1074528.0  79609657.0
2024-04-01  7311790.0  1078214.0  79078942.1
2024-07-01  7396944.0  1083897.0  78403450.8
2024-10-01  7554101.0  1094780.0  85023719.3
2025-01-01  7354051.0  1104372.0  88175341.5

[61 rows x 3 columns]

In [10]:
real_gdp

                  usa    germany       india
date
2010-01-01  4055062.0   629920.0  20696271.4
2010-04-01  4188706.0   639110.0  19091063.8
2010-07-01  4229410.0   665000.0  19374715.2
2010-10-01  4316573.0   681230.0  21337881.5
2011-01-01  4155635.0   674290.0  22833392.5
...               ...        ...         ...
2024-01-01  5647300.0  1071630.0  47820324.7
2024-04-01  5829384.0  1063850.0  44416639.5
2024-07-01  5884567.0  1083070.0  44935865.6
2024-10-01  5997184.0  1110420.0  47265418.3
2025-01-01  5776724.0  1098210.0  51351631.1

[61 rows x 3 columns]

In [11]:
# real_gdp.to_excel('quarterly_real_gdp.xlsx')
# nominal_gdp.to_excel('quarterly_nominal_gdp.xlsx')